export default {
  elements: [
    {
      type: "html",
      html: '<p class="text-onPrimary">Dispositivi utilizzati per la stomia</p>',
    },
    {
      name: "ostomy-devices-is-monoplaque",
      title: "Quale sistema di raccolta utilizza?",
      type: "boolean",
      labelTrue: "Monopezzo",
      labelFalse: "Due pezzi",
      isRequired: true,
    },
    {
      name: "ostomy-devices-plate",
      title: "Quale tipologia di placca utilizza?",
      type: "radiogroup",
      choices: [
        { value: "planar", text: "Piana" },
        { value: "convex-light", text: "Convessa leggera" },
        { value: "convex-moderate", text: "Convessa moderata" },
        { value: "convex-profonda", text: "Convessa profonda" },
        { value: "concave", text: "Concava" },
      ],
      isRequired: true,
    },
    {
      name: "ostomy-devices-plate-materials",
      title: "Com'è costituita la placca utilizzata?",
      type: "radiogroup",
      choices: [
        { value: "hydro", text: "Idrocolloide" },
        {
          value: "hydro-bandaid",
          text: "Idrocolloide + Supporto di Cerotto in TNT",
        },
        { value: "other", text: "Altro" },
      ],
      isRequired: true,
    },
    {
      name: "ostomy-devices-plate-materials-other",
      type: "text",
      title: "Indicare il materiale della placca",
      visibleIf: "{ostomy-management-plate-materials}='other'",
      isRequired: true,
    },
    {
      name: "ostomy-devices-frequency",
      title: "Ogni quanto sostituisce la placca?",
      type: "radiogroup",
      choices: [
        { value: "mutiple-times-a-day", text: "Più volte al giorno" },
        { value: "every-day", text: "Una volta al giorno" },
        { value: "every-two-days", text: "Ogni due giorni" },
        { value: "every-three-days", text: "Ogni tre giorni" },
        { value: "every-four-days", text: "Ogni quattro giorni" },
        { value: "danger", text: "Quando si stacca o c'è pericolo" },
      ],
      isRequired: true,
    },
    {
      name: "ostomy-devices-hole",
      title: "Come esegue il foro della placca?",
      type: "radiogroup",
      choices: [
        { value: "cutting", text: "Ritaglio" },
        { value: "pre-cut", text: "Pretagliata" },
        { value: "mouldable", text: "Modellabile" },
      ],
      isRequired: true,
    },
    {
      name: "ostomy-devices-accessories",
      title: "Quali dei seguenti accessori vengono utilizzati?",
      choices: [
        { value: "none", text: "Nessun accessorio" },
        { value: "alchoholic-paste", text: "Pasta con alcool" },
        { value: "non-alcoholic-paste", text: "Pasta senza alcool" },
        { value: "protective-film", text: "Film protettivo" },
        { value: "remover", text: "Remover" },
        { value: "belt", text: "Cintura" },
        { value: "rings", text: "Anelli" },
        { value: "powder", text: "Polvere" },
        { value: "other", text: "Altro" },
      ],
      type: "checkboxes",
      isRequired: true,
    },
    {
      name: "ostomy-devices-accessories-other",
      type: "text",
      title: "Indicare l'accessorio usato",
      visibleIf: "{ostomy-devices-accessories}='other'",
      isRequired: true,
    },
    {
      name: "ostomy-devices-washing",
      title:
        "Quali dei seguenti prodotti per la detersione vengono utilizzati?",
      choices: [
        { value: "soap-neutral", text: "Sapone PH neutro" },
        { value: "soap-basic", text: "Sapone PH basico" },
        { value: "gauze", text: "Garza" },
        { value: "wipes", text: "Salviette umidificate" },
        { value: "just-water", text: "Solo acqua" },
        { value: "paper", text: "Panno carta" },
        { value: "other", text: "Altro " },
      ],
      type: "checkboxes",
      isRequired: true,
    },
    {
      name: "ostomy-devices-washing-other",
      type: "text",
      title: "Indicare il detergente usato",
      visibleIf: "{ostomy-devices-accessories}='other'",
      isRequired: true,
    },
    {
      name: "ostomy-devices-is-using-additional-devices",
      title: "Utilizza presidi aggiuntivi al sistema di raccolta?",
      type: "boolean",
      labelTrue: "Sì",
      labelFalse: "No",
      isRequired: true,
    },
    {
      name: "ostomy-devices-is-using-additional-devices-yes",
      type: "text",
      title: "Quali?",
      visibleIf: "{ostomy-devices-is-using-additional-devices}=true",
      isRequired: true,
    },
    {
      name: "ostomy-devices-abs-profile",
      title: "Che tipo di profilo addominale presenta?",
      choices: [
        { value: "regular", text: "Profilo regolare" },
        { value: "outwards", text: "Profilo estroflesso" },
        { value: "inwards", text: "Profilo introflesso" },
        { value: "other", text: "Altro" },
      ],
      type: "radiogroup",
      isRequired: true,
    },
    {
      name: "ostomy-devices-abs-profile-other",
      type: "text",
      title: "Indicare il profilo",
      visibleIf: "{ostomy-devices-abs-profile}='other'",
      isRequired: true,
    },
    {
      name: "ostomy-devices-abs-everting-rate",
      title: "Dimensione grado estroflessione stomia",
      choices: [
        {
          value: "inverted",
          text: "Introflessa (profonda >9mm, moderata 5-9mm, bassa<5mm)",
        },
        {
          value: "everted",
          text: "Sul piano cutaneo o estroflessa (bassa<1cm, alta>1cm)",
        },
      ],
      type: "radiogroup",
      isRequired: true,
    },
    {
      name: "ostomy-devices-has-difficulties",
      title:
        "Ha difficoltà di accesso alla fornitura di dispositivi e accessori?",
      type: "boolean",
      labelTrue: "Sì",
      labelFalse: "No",
      isRequired: true,
    },
    {
      name: "ostomy-devices-has-own-devices",
      title: "Ha dovuto integrare a sue spese la fornitura?",
      type: "boolean",
      labelTrue: "Sì",
      labelFalse: "No",
      isRequired: true,
    },
    {
      name: "ostomy-devices-has-own-devices-yes",
      title: "Per quale prodotto?",
      type: "radiogroup",
      choices: [
        { value: "gather", text: "Sistema di raccolta" },
        { value: "accessories", text: "Accessori" },
      ],
      visibleIf: "{ostomy-devices-has-own-devices}=true",
      isRequired: true,
    },
  ],
};
